package vn.com.luanvan.model;

// default package
// Generated Jan 31, 2015 7:09:10 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PhanloaiId generated by hbm2java
 */
@SuppressWarnings("serial")
@Embeddable
public class DiagramUsecaseId implements java.io.Serializable {

	private int usecaseid;
	private int diagramid;

	public DiagramUsecaseId() {
	}

	@Column(name = "USECASEID", nullable = false)
	public int getUsecaseid() {
		return this.usecaseid;
	}

	public void setUsecaseid(int usecaseid) {
		this.usecaseid = usecaseid;
	}

	@Column(name = "DIAGRAMID", nullable = false)
	public int getDiagramid() {
		return diagramid;
	}

	public void setDiagramid(int diagramid) {
		this.diagramid = diagramid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DiagramUsecaseId))
			return false;
		DiagramUsecaseId castOther = (DiagramUsecaseId) other;

		return (this.getUsecaseid() == castOther.getUsecaseid())
				&& (this.getDiagramid() == castOther.getDiagramid());
	}

}
