package vn.com.luanvan.model;

// default package
// Generated Jan 31, 2015 7:09:10 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PhanloaiId generated by hbm2java
 */
@Embeddable
public class DiagramActorId implements java.io.Serializable {

	private int actorid;
	private int diagramid;

	public DiagramActorId() {
	}

	@Column(name = "ACTORID", nullable = false)
	public int getActorid() {
		return this.actorid;
	}

	public void setActorid(int actorid) {
		this.actorid = actorid;
	}

	@Column(name = "DIAGRAMID", nullable = false)
	public int getDiagramid() {
		return diagramid;
	}

	public void setDiagramid(int diagramid) {
		this.diagramid = diagramid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DiagramActorId))
			return false;
		DiagramActorId castOther = (DiagramActorId) other;

		return (this.getActorid() == castOther.getActorid())
				&& (this.getDiagramid() == castOther.getDiagramid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getActorid();
		result = 37 * result + this.getDiagramid();
		return result;
	}

}
