package vn.com.luanvan.model;

// default package
// Generated Jan 31, 2015 7:09:10 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * GiatriluongId generated by hbm2java
 */
@SuppressWarnings("serial")
@Embeddable
public class GiatriluongId implements java.io.Serializable {

	private int projectid;
	private int luongid;

	public GiatriluongId(){
		
	}

	public GiatriluongId(int projectid, int luongid) {
		this.projectid = projectid;
		this.luongid = luongid;
	}

	@Column(name = "PROJECTID", nullable = false)
	public int getProjectid() {
		return this.projectid;
	}

	public void setProjectid(int projectid) {
		this.projectid = projectid;
	}

	@Column(name = "LUONGID", nullable = false)
	public int getLuongId() {
		return this.luongid;
	}

	public void setLuongId(int luongid) {
		this.luongid = luongid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GiatriluongId))
			return false;
		GiatriluongId castOther = (GiatriluongId) other;

		return (this.getProjectid() == castOther.getProjectid())
				&& (this.getLuongId() == castOther.getLuongId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getProjectid();
		result = 37 * result + this.getLuongId();
		return result;
	}

}
