package vn.com.luanvan.model;

// default package
// Generated Jan 31, 2015 7:09:10 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OrderBy;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Nhomchucnang generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "nhomchucnang")
public class Nhomchucnang implements java.io.Serializable {

	private Integer nhomid;
	private String tennhom;
	private Project project;
	private Set<Chucnang> chucnangs = new HashSet<Chucnang>(0);

	public Nhomchucnang() {
	}

	public Nhomchucnang(String tennhom) {
		this.tennhom = tennhom;
	}

	public Nhomchucnang(String tennhom, Set<Chucnang> chucnangs) {
		this.tennhom = tennhom;
		this.chucnangs = chucnangs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "NHOMID", unique = true, nullable = false)
	public Integer getNhomid() {
		return this.nhomid;
	}

	public void setNhomid(Integer nhomid) {
		this.nhomid = nhomid;
	}

	@Column(name = "TENNHOM", nullable = false)
	public String getTennhom() {
		return this.tennhom;
	}

	public void setTennhom(String tennhom) {
		this.tennhom = tennhom;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "nhomchucnang")
	@OrderBy("motayeucau")
	public Set<Chucnang> getChucnangs() {
		return this.chucnangs;
	}

	public void setChucnangs(Set<Chucnang> chucnangs) {
		this.chucnangs = chucnangs;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "PROJECTID", nullable = false)
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}
}
