package vn.com.luanvan.model;

// default package
// Generated Jan 31, 2015 7:09:10 PM by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * xephangmoitruong generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "xephangmoitruong")
public class Xephangmoitruong implements java.io.Serializable {

	private XephangmoitruongId id;
	private Hesomoitruong hesomoitruong;
	private Project project;
	private Integer giatrixephang;
	private float ondinh;

	public Xephangmoitruong() {
	}

	public Xephangmoitruong(XephangmoitruongId id, Hesomoitruong hesomoitruong,
			Project project) {
		this.id = id;
		this.hesomoitruong = hesomoitruong;
		this.project = project;
	}

	public Xephangmoitruong(XephangmoitruongId id, Hesomoitruong hesomoitruong,
			Project project, Integer giatrixephang, float ondinh) {
		this.id = id;
		this.hesomoitruong = hesomoitruong;
		this.project = project;
		this.giatrixephang = giatrixephang;
		this.ondinh = ondinh;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "projectid", column = @Column(name = "PROJECTID", nullable = false)),
			@AttributeOverride(name = "hesomoitruongid", column = @Column(name = "HESOMOITRUONGID", nullable = false)) })
	public XephangmoitruongId getId() {
		return this.id;
	}

	public void setId(XephangmoitruongId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "HESOMOITRUONGID", nullable = false, insertable = false, updatable = false)
	public Hesomoitruong getHesomoitruong() {
		return this.hesomoitruong;
	}

	public void setHesomoitruong(Hesomoitruong hesomoitruong) {
		this.hesomoitruong = hesomoitruong;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PROJECTID", nullable = false, insertable = false, updatable = false)
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	@Column(name = "GIATRIXEPHANG")
	public Integer getGiatrixephang() {
		return this.giatrixephang;
	}

	public void setGiatrixephang(Integer giatrixephang) {
		this.giatrixephang = giatrixephang;
	}

	@Column(name = "ONDINH")
	public float getOndinh() {
		return this.ondinh;
	}

	public void setOndinh(float f) {
		this.ondinh = f;
	}

}
