package vn.com.luanvan.model;


import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Project generated by hbm2java
 */
@Entity
@Table(name = "project", catalog = "luanvan2")
public class Project implements java.io.Serializable {

	private int projectid;
	private User user;
	private String name;
	private int tfw;
	private String programskill;
	private String knowledgerequired;
	private String understandprocess;
	private int status;
	private String description;

	public Project() {
	}

	public Project(int projectid, User user, String name, int tfw,
			String programskill, String knowledgerequired,
			String understandprocess, int status) {
		this.projectid = projectid;
		this.user = user;
		this.name = name;
		this.tfw = tfw;
		this.programskill = programskill;
		this.knowledgerequired = knowledgerequired;
		this.understandprocess = understandprocess;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "PROJECTID", unique = true, nullable = false)
	public int getProjectid() {
		return this.projectid;
	}

	public void setProjectid(int projectid) {
		this.projectid = projectid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USERNAME", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "NAME", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "TFW")
	public int getTfw() {
		return this.tfw;
	}

	public void setTfw(int tfw) {
		this.tfw = tfw;
	}

	@Column(name = "PROGRAMSKILL", length = 999)
	public String getProgramskill() {
		return this.programskill;
	}

	public void setProgramskill(String programskill) {
		this.programskill = programskill;
	}

	@Column(name = "KNOWLEDGEREQUIRED", length = 999)
	public String getKnowledgerequired() {
		return this.knowledgerequired;
	}

	public void setKnowledgerequired(String knowledgerequired) {
		this.knowledgerequired = knowledgerequired;
	}

	@Column(name = "UNDERSTANDPROCESS", length = 999)
	public String getUnderstandprocess() {
		return this.understandprocess;
	}

	public void setUnderstandprocess(String understandprocess) {
		this.understandprocess = understandprocess;
	}

	@Column(name = "STATUS", nullable = false)
	public int isStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}
	
	@Column(name = "DESCRIPTION", length = 255)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
