package vn.com.luanvan.model;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "luanvan2")
public class User implements java.io.Serializable {

	private String username;
	private String password;
	private boolean enabled;
	private String email;
	private String image;
	private String phone;
	private String address;
	private String name;
	private Set<Project> projects = new HashSet<Project>(0);
	private Set<UserRole> userroles = new HashSet<UserRole>(0);

	public User() {
	}

	public User(String username, String password, boolean enabled, String email, String image, String phone, String address, String name) {
		this.username = username;
		this.password = password;
		this.enabled = enabled;
		this.email = email;
		this.image = image;
		this.phone = phone;
		this.address = address;
		this.name = name;
	}

	public User(String username, String password, boolean enabled,
			String email, Set<Project> projects, Set<UserRole> userroles, String image, String name, String phone, String address) {
		this.username = username;
		this.password = password;
		this.enabled = enabled;
		this.email = email;
		this.projects = projects;
		this.userroles = userroles;
		this.image = image;
		this.phone = phone;
		this.address = address;
		this.name = name;
	}

	@Id
	@Column(name = "USERNAME", unique = true, nullable = false, length = 45)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "PASSWORD", nullable = false, length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "ENABLED", nullable = false, precision = 1, scale = 0)
	public boolean isEnabled() {
		return this.enabled;
	}

	public void setEnabled(boolean enabled) {
		this.enabled = enabled;
	}

	@Column(name = "EMAIL", nullable = false)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Project> getProjects() {
		return this.projects;
	}

	public void setProjects(Set<Project> projects) {
		this.projects = projects;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<UserRole> getUserroles() {
		return this.userroles;
	}

	public void setUserroles(Set<UserRole> userroles) {
		this.userroles = userroles;
	}
	@Column(name = "IMAGE")
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}
	@Column(name = "PHONE", length = 12)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}
	
	@Column(name = "NAME", length = 255)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
	
	@Column(name = "ADDRESS", length = 999)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}
	
}
