package vn.com.luanvan.model;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import static javax.persistence.GenerationType.IDENTITY;



/**
 * Userrole generated by hbm2java
 */
@Entity
@Table(name = "userrole", catalog = "luanvan2")
public class UserRole implements java.io.Serializable {

	private int userroleid;
	private User user;
	private String role;

	public UserRole() {
	}

	public UserRole(int userroleid, User user, String role) {
		this.userroleid = userroleid;
		this.user = user;
		this.role = role;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "USERROLEID", unique = true, nullable = false)
	public int getUserroleid() {
		return this.userroleid;
	}

	public void setUserroleid(int userroleid) {
		this.userroleid = userroleid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USERNAME", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "ROLE", nullable = false, length = 45)
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

}
