package vn.com.luanvan.model;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "luanvan2")
public class User implements java.io.Serializable {

	private String username;
	private String password;
	private boolean enabled;
	private String email;
	private Set<Project> projects = new HashSet<Project>(0);
	private Set<UserRole> userroles = new HashSet<UserRole>(0);

	public User() {
	}

	public User(String username, String password, boolean enabled, String email) {
		this.username = username;
		this.password = password;
		this.enabled = enabled;
		this.email = email;
	}

	public User(String username, String password, boolean enabled,
			String email, Set<Project> projects, Set<UserRole> userroles) {
		this.username = username;
		this.password = password;
		this.enabled = enabled;
		this.email = email;
		this.projects = projects;
		this.userroles = userroles;
	}

	@Id
	@Column(name = "USERNAME", unique = true, nullable = false, length = 45)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "PASSWORD", nullable = false, length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "ENABLED", nullable = false, precision = 1, scale = 0)
	public boolean isEnabled() {
		return this.enabled;
	}

	public void setEnabled(boolean enabled) {
		this.enabled = enabled;
	}

	@Column(name = "EMAIL", nullable = false)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Project> getProjects() {
		return this.projects;
	}

	public void setProjects(Set<Project> projects) {
		this.projects = projects;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<UserRole> getUserroles() {
		return this.userroles;
	}

	public void setUserroles(Set<UserRole> userroles) {
		this.userroles = userroles;
	}

}
