package vn.com.luanvan.model;

// default package
// Generated Jan 31, 2015 7:09:10 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.CascadeType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Usecase generated by hbm2java
 */
@Entity
@Table(name = "usecase", catalog = "luanvan")
public class Usecase implements java.io.Serializable {

	private String usecaseid;
	private Bmt bmt;
	private Nhomuc nhomuc;
	private Project project;
	private String nameofuc;
	private String motauc;
	private String cauhoi;
	private int tinhtien;
	private Set<File> files = new HashSet<File>(0);
	private Set<Phanloai> phanloais = new HashSet<Phanloai>(0);
	private Set<Chucnang> chucnangs = new HashSet<Chucnang>(0);

	public Usecase() {
	}

	public Usecase(Bmt bmt, Nhomuc nhomuc, Project project, String nameofuc, String motauc, int tinhtien) {
		this.bmt = bmt;
		this.nhomuc = nhomuc;
		this.project = project;
		this.nameofuc = nameofuc;
		this.motauc = motauc;
		this.tinhtien = tinhtien;
	}

	public Usecase(Bmt bmt, Nhomuc nhomuc, Project project, String nameofuc, String motauc,
			String cauhoi, int tinhtien, Set<File> files, Set<Phanloai> phanloais, Set<Chucnang> chucnangs) {
		this.bmt = bmt;
//		this.mucdo = mucdo;
//		this.mucdocanthiet = mucdocanthiet;
		this.nhomuc = nhomuc;
		this.project = project;
		this.nameofuc = nameofuc;
		this.motauc = motauc;
		this.cauhoi = cauhoi;
		this.tinhtien = tinhtien;
		this.files = files;
		this.phanloais = phanloais;
		this.chucnangs = chucnangs;
	}

	@Id
//	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "USECASEID", unique = true, nullable = false)
	public String getUsecaseid() {
		return this.usecaseid;
	}

	public void setUsecaseid(String usecaseid) {
		this.usecaseid = usecaseid;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "BMTID", nullable = false)
	public Bmt getBmt() {
		return this.bmt;
	}

	public void setBmt(Bmt bmt) {
		this.bmt = bmt;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NHOMUCID")
	public Nhomuc getNhomuc() {
		return this.nhomuc;
	}

	public void setNhomuc(Nhomuc nhomuc) {
		this.nhomuc = nhomuc;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PROJECTID", nullable = false)
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	@Column(name = "NAMEOFUC", nullable = false)
	public String getNameofuc() {
		return this.nameofuc;
	}

	public void setNameofuc(String nameofuc) {
		this.nameofuc = nameofuc;
	}

	@Column(name = "MOTAUC", nullable = false, length = 65535)
	public String getMotauc() {
		return this.motauc;
	}

	public void setMotauc(String motauc) {
		this.motauc = motauc;
	}

	@Column(name = "CAUHOI", length = 65535)
	public String getCauhoi() {
		return this.cauhoi;
	}

	public void setCauhoi(String cauhoi) {
		this.cauhoi = cauhoi;
	}

	@Column(name = "TINHTIEN", nullable = false)
	public int getTinhtien() {
		return this.tinhtien;
	}

	public void setTinhtien(int tinhtien) {
		this.tinhtien = tinhtien;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usecase")
	public Set<File> getFiles() {
		return this.files;
	}

	public void setFiles(Set<File> files) {
		this.files = files;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "usecase", cascade = CascadeType.REMOVE)
	public Set<Phanloai> getPhanloais() {
		return this.phanloais;
	}

	public void setPhanloais(Set<Phanloai> phanloais) {
		this.phanloais = phanloais;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usecase")
	public Set<Chucnang> getChucnangs() {
		return this.chucnangs;
	}

	public void setChucnangs(Set<Chucnang> chucnangs) {
		this.chucnangs = chucnangs;
	}

}
