package vn.com.luanvan.model;

// default package
// Generated Jan 31, 2015 7:09:10 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Mucluongnhanuoc generated by hbm2java
 */
@Entity
@Table(name = "trongsonoluc", catalog = "luanvan")
public class Trongsonoluc implements java.io.Serializable {

	private int trongsoid;
	private String mota;
	private double giatri;


	public Trongsonoluc(){
		
	}
	public Trongsonoluc(int trongsoid, String mota, double giatri) {
		this.trongsoid = trongsoid;
		this.mota = mota;
		this.giatri = giatri;
	}

	@Id
	@Column(name = "TRONGSOID", unique = true, nullable = false)
	public int getTrongsoid() {
		return this.trongsoid;
	}
	
	public void setTrongsoid(int trongso) {
		this.trongsoid = trongso;
	}
	@Column(name = "MOTA")
	public String getMota() {
		return mota;
	}
	public void setMota(String mota) {
		this.mota = mota;
	}
	@Column(name = "GIATRI")
	public double getGiatri() {
		return giatri;
	}
	public void setGiatri(double giatri) {
		this.giatri = giatri;
	}

}
